services:
  postgres:
    container_name: erp-postgres
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "60100:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks: [infra]

  backup:
    image: mazzolino/restic
    container_name: erp-restic
    profiles: [production]
    restart: unless-stopped
    env_file: restic.env
    networks: [infra]
    environment:
      BACKUP_CRON: "0 2 * * *"
      RUN_ON_STARTUP: "true"
      TZ: Europe/Moscow
      RESTIC_BACKUP_ARGS: "--verbose"
      RESTIC_FORGET_ARGS: "--keep-daily 30"
      PRE_COMMANDS: |-
        mkdir -p /data/
        docker exec erp-postgres pg_dumpall -U postgres --clean > /data/factory_piek.sql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # We need to communicate with docker
      - cache:/cache

networks:
  infra:
    name: infra
    driver: bridge
    external: true

volumes:
  cache:
  db_data:
