mutation InsertDocsArrayMutation($objects: [attachments_insert_input!]!) {
  insert_attachments(objects: $objects) {
    affected_rows
    returning {
      id
      key
      size
      uploaded_at
      filename
    }
  }
}

mutation DeleteDocsMutation($key: String!) {
  delete_orders_attachments(where: { key: { _eq: $key } }) {
    affected_rows
    returning {
      id
      key
    }
  }
}

mutation InsertOrderAttachemnts(
  $attachments: [orders_order_attachments_insert_input!]!
) {
  insert_orders_order_attachments(objects: $attachments) {
    affected_rows
  }
}

mutation InsertDetailAttachemnts(
  $detailAttachments: [metal_flow_detail_attachments_insert_input!]!
) {
  insert_metal_flow_detail_attachments(objects: $detailAttachments) {
    affected_rows
  }
}
