fragment MaterialFragment on metal_pdo_materials {
  id
  unit
  shape
  shape_data
}

query GetMaterials {
  metal_pdo_materials {
    ...MaterialFragment
  }
}

query GetMaterialByPk($id: Int!) {
  metal_pdo_materials_by_pk(id: $id) {
    ...MaterialFragment
  }
}

query GetCirclePossibleAlloys($_eq: Int!) {
  metal_pdo_materials(where: { shape: { _eq: $_eq } }) {
    shape_data(path: "alloy")
  }
}

mutation InsertMaterial($object: metal_pdo_materials_insert_input!) {
  insert_metal_pdo_materials_one(object: $object) {
    id
  }
}

mutation UpdateMaterial($id: Int!, $_set: metal_pdo_materials_set_input!) {
  update_metal_pdo_materials_by_pk(pk_columns: { id: $id }, _set: $_set) {
    id
  }
}

mutation DeleteMaterial($id: Int!) {
  delete_metal_pdo_materials_by_pk(id: $id) {
    id
  }
}
