query GetAllUsers {
  users {
    first_name
    last_name
    id
    role
  }
}

query GetOrderPayments($_eq: Int!) {
  orders_order_payments(
    where: { order_id: { _eq: $_eq } }
    order_by: { date: asc }
  ) {
    date
    id
    amount
  }
}

mutation InsertNotification(
  $comment_id: Int!
  $user_id: Int!
  $order_id: Int!
) {
  insert_orders_notifications(
    objects: {
      comment_id: $comment_id
      user_id: $user_id
      order_id: $order_id
    }
  ) {
    returning {
      user_id
      id
    }
  }
}

# DOCS
mutation InsertDocumentsArray($objects: [orders_attachments_insert_input!]!) {
  insert_orders_attachments(objects: $objects) {
    returning {
      id
    }
  }
}

mutation InsertPayment($amount: numeric!, $date: timestamp!, $order_id: Int!) {
  insert_orders_order_payments_one(
    object: { amount: $amount, order_id: $order_id, date: $date }
  ) {
    id
    order_id
  }
}

mutation DeletePayment($id: Int!) {
  delete_orders_order_payments_by_pk(id: $id) {
    id
  }
}

mutation DeleteOrder($id: Int!) {
  delete_orders_orders_by_pk(id: $id) {
    id
  }
}

mutation InsertOrderItem(
  $name: String!
  $order_id: Int!
  $quantity: Int!
  $description: String!
) {
  insert_orders_order_items_one(
    object: {
      order_id: $order_id
      name: $name
      description: $description
      quantity: $quantity
    }
  ) {
    id
    order_id
  }
}

mutation DeleteOrderItemByPk($id: Int!) {
  delete_orders_order_items_by_pk(id: $id) {
    id
  }
}

mutation UpdateOrderItemByPk($id: Int!, $_set: orders_order_items_set_input!) {
  update_orders_order_items_by_pk(pk_columns: {id: $id}, _set: $_set) {
    id
  }
}


mutation MoveOrderToPriority($id: Int!, $acceptance_date: timestamp!) {
  update_orders_orders_by_pk(
    pk_columns: { id: $id }
    _set: { status: 2, acceptance_date: $acceptance_date }
  ) {
    id
    status
  }
}

mutation MoveOrderToArchive(
  $id: Int!
  $actual_shipping_date: timestamp!
  $status: Int!
) {
  update_orders_orders_by_pk(
    pk_columns: { id: $id }
    _set: {
      status: $status
      awaiting_dispatch: false
      actual_shipping_date: $actual_shipping_date
    }
  ) {
    id
    status
  }
}

mutation UpdateNeedAttention($id: Int!, $need_attention: String!) {
  update_orders_orders_by_pk(
    pk_columns: { id: $id }
    _set: { need_attention: $need_attention }
  ) {
    id
    need_attention
  }
}

mutation UpdateAwaitingDispatch($id: Int!, $awaiting_dispatch: Boolean!) {
  update_orders_orders_by_pk(
    pk_columns: { id: $id }
    _set: { awaiting_dispatch: $awaiting_dispatch }
  ) {
    id
    awaiting_dispatch
  }
}

mutation UpdateOrderInfo($id: Int!, $fields: orders_orders_set_input) {
  update_orders_orders_by_pk(pk_columns: { id: $id }, _set: $fields) {
    id
    contractor
    city
    created_at
  }
}
