query GetReclamationOrders {
  orders_orders(where: { status: { _in: [10, 11, 12] } }) {
    ...Order
  }
}

mutation UpdateOrderStatus($id: Int!, $status: Int!) {
  update_orders_orders_by_pk(
    pk_columns: { id: $id }
    _set: { status: $status }
  ) {
    id
    status
  }
}
