query getOrdersByStatus(
  $shipping_date: order_by = asc_nulls_first
  $order_status: Int!
) {
  orders_orders(
    where: { status: { _eq: $order_status } }
    order_by: { shipping_date: $shipping_date }
  ) {
    ...Order
  }
}

query getOrdersArchivedBySearchKeyword($keyword: String!, $order_status: Int!) {
  orders_orders(
    order_by: { actual_shipping_date: desc_nulls_last }
    where: {
      _or: [
        { contractor: { _ilike: $keyword } }
        { invoice_number: { _ilike: $keyword, _is_null: false } }
      ]
      status: { _eq: $order_status }
    }
  ) {
    ...Order
  }
}

query GetOrdersArchivedByInterval($_lte: timestamp!, $_gte: timestamp!) {
  orders_orders(
    where: { actual_shipping_date: { _lte: $_lte, _gte: $_gte } }
    order_by: { actual_shipping_date: asc }
  ) {
    ...Order
  }
}

query GetManagers {
  users(where: { role: { _eq: 2 } }) {
    first_name
    last_name
    id
    role
  }
}

query GetOrderByPK($id: Int!) {
  orders_orders(where: { id: { _eq: $id } }) {
    ...Order
  }
}

query GetOrderAttachments($order_id: Int!) {
  orders_attachments(where: { order_id: { _eq: $order_id } }) {
    filename
    id
    key
    size
  }
}

mutation InsertOrder($object: orders_orders_insert_input!) {
  insert_orders_orders_one(object: $object) {
    id
  }
}



query GetDistinctCities {
  orders_orders(distinct_on: city) {
    city
  }
}

query GetDistinctContractors {
  orders_orders(distinct_on: contractor) {
    contractor
  }
}

query GetOrderPositions($order_id: Int!) {
  orders_order_items(where: { order_id: { _eq: $order_id } }) {
    id
    name
    description
    quantity
  }
}