fragment Order on orders_orders {
  id
  status 
  city
  contractor
  invoice_number
  total_amount
  order_number
  need_attention
  awaiting_dispatch
  actual_shipping_date
  acceptance_date
  shipping_date
  created_at
  manager_id
  comment
  user {
    id
    email
    first_name
    last_name
  }
  order_items(order_by: { id: asc }) {
    id
    name
    description
    quantity
  }
  order_payments(where: { amount: { _neq: 0 } }) {
    id
    amount
    date
  }
}