/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The events we actually observe in the system.
 *
 * Important:
 * - Events are instantaneous points in time (badge swipes).
 * - They do not describe duration or state by themselves.
 *
 * From events we derive *time intervals* (deltas),
 * and only those intervals can meaningfully be associated with
 * a hidden state such as "Inside" or "Outside"
 */
export interface Event {
  id: number
  card: string
  timestamp: string
}

export declare function runHiddenMarkovModel(events: Array<Event>): Array<WorkInterval>

export declare function trainHiddenMarkovModel(): void

export interface WorkInterval {
  entry: number
  exit?: number
}
