/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Event {
  id: number
  card: string
  timestamp: string
}

/** HMM solves the problem of deciding inside vs outside for each swipe by using the entire sequence context, not just individual time gaps. */
export declare function runHiddenMarkovModel(allEvents: Array<Event>): number
