subscription Comments($OrderID: Int!) {
  orders_comments(where: { order_id: { _eq: $OrderID } }, order_by: { id: desc }) {
    id
    text
    created_at
    user {
      id
      first_name
      last_name
    }
  }
}

mutation InsertComment($OrderID: Int!, $Text: String!, $UserID: Int!) {
  insert_orders_comments_one(object: { order_id: $OrderID, text: $Text, user_id: $UserID }) {
    id
    order_id
    text
    created_at
    user_id
  }
}

mutation DeleteComment($CommentID: Int!) {
  delete_orders_comments_by_pk(id: $CommentID) {
    id
  }
}

mutation UpdateComment($CommentID: Int!, $Text: String!) {
  update_orders_comments_by_pk(pk_columns: { id: $CommentID }, _set: { text: $Text }) {
    id
    order_id
    text
    created_at
    user_id
  }
}
