query GetDetails {
  metal_flow_details {
    id
    name
    detail_materials {
      data
      material {
        ...MaterialFragment
      }
    }
  }
}

query GetDetailByPk($id: Int!) {
  metal_flow_details_by_pk(id: $id) {
    id
    name
    detail_materials {
      data
      material {
        ...MaterialFragment
      }
    }
  }
}

mutation InsertDetail($object: metal_flow_details_insert_input!) {
  insert_metal_flow_details_one(object: $object) {
    id
    name
  }
}

mutation UpdateDetail($_set: metal_flow_details_set_input!, $id: Int!) {
  update_metal_flow_details_by_pk(pk_columns: { id: $id }, _set: $_set) {
    id
  }
}

mutation UpdateDetailMaterialRelationData(
  $detail_id: Int!
  $material_id: Int!
  $data: jsonb!
) {
  update_metal_flow_detail_materials_by_pk(
    pk_columns: { detail_id: $detail_id, material_id: $material_id }
    _set: { data: $data }
  ) {
    data
  }
}

mutation DeleteDetail($id: Int!) {
  delete_metal_flow_details_by_pk(id: $id) {
    id
  }
}

query GetDetailMaterials($_eq: Int!) {
  metal_flow_detail_materials(where: { material_id: { _eq: $_eq } }) {
    material {
      ...MaterialFragment
    }
  }
}

query GetDetailsMadeFromThatMaterial($_eq: Int!) {
  metal_flow_detail_materials(where: { material_id: { _eq: $_eq } }) {
    detail {
      id
      name
    }
  }
}

mutation InsertDetailMaterials(
  $objects: [metal_flow_detail_materials_insert_input!]!
) {
  insert_metal_flow_detail_materials(
    objects: $objects
    on_conflict: { constraint: detail_materials_p_key }
  ) {
    affected_rows
    returning {
      detail_id
      material_id
    }
  }
}