mutation InsertDocsArrayMutation($objects: [orders_attachments_insert_input!]!) {
  insert_orders_attachments(objects: $objects) {
    returning {
      id
      key
    }
  }
}

mutation DeleteDocsMutation($key: String!) {
  delete_orders_attachments(where: { key: { _eq: $key } }) {
    returning {
      key
    }
  }
}
