query AllOrdersPaymentsDataQuery {
  orders_orders(where: { status: { _eq: 3 } }, order_by: { id: desc }) {
    id
    total_amount
  }
}

query UnpaidOrdersQuery($unpaidIDs: [Int!], $OrderStatus: Int!) {
  orders_orders(
    where: { status: { _eq: $OrderStatus }, id: { _in: $unpaidIDs } }
  ) {
    id
    contractor
    invoice_number
    city
    status
    shipping_date
    total_amount
    awaiting_dispatch
    actual_shipping_date
    created_at
    manager_id
    order_items {
      id
      quantity
      name
    }
    user {
      first_name
      last_name
    }
  }
}
