query AllTokensQuery {
  refresh_tokens {
    id
    token
    user {
      id
      first_name
      last_name
      email
      role
    }
  }
}

mutation InsertTokenMutation($user_id: Int!, $token: String!) {
  insert_refresh_tokens(objects: { user_id: $user_id, token: $token }) {
    returning {
      id
    }
  }
}

mutation DeleteTokenMutation($token: String!) {
  delete_refresh_tokens(where: { token: { _eq: $token } }) {
    returning {
      id
    }
  }
}

mutation UpdateTokenMutation($token_id: Int!, $token: String!) {
  update_refresh_tokens_by_pk(
    pk_columns: { id: $token_id }
    _set: { token: $token }
  ) {
    id
    user_id
  }
}
